### ISSUE TITLE
64 Bit Version of pcre3.dll

### ISSUE THREAD

**Issue by lievencardoen** [gabsoftware/Progress-ABL-4GL-Regex#1]
Hi, is there a 64 bit version of pcre3.dll ?

I'm trying this out with OpenEdge 12.2 - 64 Bit... Or a anycpu version?

Can't seem to find anything online...

Thx, Lieven Cardoen

**Comment by lievencardoen** [comment]
Do you have the source code for creating the pcre3.dll?

I see there's a pcre_compile2 call which I can't find in the current pcre libraries. Probably a wrapper?

Also, when trying out another libpcre2-8.dll, I constantly get an error saying

Could not find the entrypoint _pcre2_compile2@48. (3260)

My knowledge of C is not that big... why does it prefix _ to the method call?

**Comment by gabsoftware** [comment]
I found the source code for the Windows version but it's for PCRE 2.

https://github.com/PCRE2Project/pcre2/releases

**Comment by gabsoftware** [comment]
I found where the pcre3.dll comes from. It's from the GnuWin32 project.

https://sourceforge.net/projects/gnuwin32/files/pcre/

Try version 7, bin package. There's also the source code.

**Comment by gabsoftware** [comment]
Update:

You can build a copy of pcre DLL yourself (even x64) by getting it at
https://sourceforge.net/projects/pcre/files/
and opening the folder in Visual Studio.
Configure it to build the shared libraries and support JIT compilation.
Then define PCRE_LIB preprocessor variable to whatever DLL name you have.
I built and included a Release version of PCRE with shared libs, JIT, UTF8 support
both in 32 bits (x86) and 64 bits (x64) and I renamed the resulting pcre.dll
to pcre-msvc-x64.dll and pcre-msvc-x86.dll.
